# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Max Mehl

changelog:
  categories:
    - title: Dependencies
      labels:
        - Renovate
        - dependencies
    - title: Features and Fixes
      labels:
        - "*"
